### ISSUE TITLE
README.md discrepancy

### ISSUE THREAD

**Issue by tippenring** [mdObject/GECentricity#4]
I'm running CPS 12.3. 

The README.md file states the default HTML encounter form path is "%JBOSS.SERVER.HOME.DIR%\server\default\deploy\demo.ear\CentricityPracticeWS.war\"

In our environment, the default location for HTML forms is "C:\Program Files\Centricity Practice Solution\jboss\standalone\deployments\<instance name>.ear\CentricityPracticeWS.war". 

Additionally, the environment variable %JBOSS.SERVER.HOME.DIR% is undefined.

**Comment by aaltotsky** [comment]
You are correct. Your environment is a bit different. In the README.md we pointed to a demo installation. For production installation, you may see a different path.
